version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3700:3700"
    environment:
      - NODE_ENV=development
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/data/competitive_landscape.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_KEY=${API_KEY:-dev-api-key}
      - LOG_LEVEL=info
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3700/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/data/competitive_landscape.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=info
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: MySQL for production-like testing
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=competitive_analysis_db
      - MYSQL_USER=competitive_user
      - MYSQL_PASSWORD=competitive_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./migrations/001_initial_schema_mysql.sql:/docker-entrypoint-initdb.d/01_schema.sql
    profiles:
      - mysql

volumes:
  mysql_data: